# Picture caching folder settings
caching_folder:
  # Path to the picture folder
  path: /tmp/pictures
# Image processing settings
image_processing:
  # Resize images to this width (max 512)
  width: 512
  # Resize images to this height (max 512)
  height: 306
  # Number of images to download (max 50)
  quantify: 50
  # Duration period per Picture
  duration: 3
# Unsplash API settings
unsplash:
  # Unsplash API access key
  access_key: 1234567890
  # Unsplash API secret key
  secret_key: 1234567890
  # Unsplash API Search Pattern
  search_pattern: mountain